### ISSUE TITLE
building notebook fails

### ISSUE THREAD

**Issue by joemcglinchy** [PlatformStories/gbdx-notebook#1]
Hello, I tried building the jupyter notebook with gbdxtools using docker in Windows 10 with the following command from windows Powershell (administrator):

`docker build -f .\Dockerfile .`

Here is the output I see. It has failed to build some python packages and perhaps other things:
PS C:\Users\jomc9287\gbdx-notebook> docker build -f .\Dockerfile .
Sending build context to Docker daemon  100.9kB
Step 1/9 : FROM jupyter/scipy-notebook:2d878db5cbff
2d878db5cbff: Pulling from jupyter/scipy-notebook
fdd5d7827f33: Pull complete
a3ed95caeb02: Pull complete
f08e494cf5cc: Pull complete
6548f4aff175: Pull complete
d762b5abb43e: Pull complete
c841d1ad6a8e: Pull complete
78ff99539390: Pull complete
ca1e42ffa07b: Pull complete
a2e91df52de2: Pull complete
b653922de2b8: Pull complete
1aff6b8f4bde: Pull complete
6693b52f757b: Pull complete
85562a53de6b: Pull complete
40c1ea0555e5: Pull complete
23289d43a722: Pull complete
88ebca24cf71: Pull complete
7b6f421a86c4: Pull complete
9b8b809ef2af: Pull complete
Digest: sha256:1814676c498f928d33b7533923bcbc2fb5f80f1a35a2de4b1cbaac0fc3a0b37b
Status: Downloaded newer image for jupyter/scipy-notebook:2d878db5cbff
 ---> cac691e0ae7f
Step 2/9 : MAINTAINER Kostas Stamatiou <kostas.stamatiou@digitalglobe.com>
 ---> Running in a5f80b4e3392
 ---> ec03c3ab5068
Removing intermediate container a5f80b4e3392
Step 3/9 : USER root
 ---> Running in 6583dbc3c4ac
 ---> 4d3c55ca0cda
Removing intermediate container 6583dbc3c4ac
Step 4/9 : RUN apt-get update &&     apt-get install -y --no-install-recommends gdal-bin &&     apt-get clean &&     rm
-rf /var/lib/apt/lists/* &&     rm /bin/sh && ln -s /bin/bash /bin/sh  # default command interpreter is bash
 ---> Running in bdb6b3f46fad
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://httpredir.debian.org jessie InRelease
Get:2 http://httpredir.debian.org jessie-updates InRelease [145 kB]
Get:3 http://httpredir.debian.org jessie Release.gpg [2,373 B]
Get:4 http://httpredir.debian.org jessie Release [148 kB]
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [555 kB]
Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.8 kB]
Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9,063 kB]
Fetched 9,995 kB in 4s (2,135 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libarmadillo4 libarpack2 libblas-common libblas3 libdap11 libdapclient3
  libdapserver7 libepsilon1 libfreexl1 libgdal1h libgeos-3.4.2 libgeos-c1
  libgfortran3 libhdf4-0-alt libhdf5-8 libkml0 liblapack3 libmysqlclient18
  libnetcdfc7 libodbc1 libogdi3.2 libpopt0 libpq5 libproj0 libspatialite5
  liburiparser1 libwebp5 libxerces-c3.1 mysql-common odbcinst odbcinst1debian2
  proj-data
Suggested packages:
  python-gdal libhdf4-doc libhdf4-alt-dev hdf4-tools libnetcdf4 libmyodbc
  odbc-postgresql tdsodbc unixodbc-bin ogdi-bin
Recommended packages:
  proj-bin
The following NEW packages will be installed:
  gdal-bin libarmadillo4 libarpack2 libblas-common libblas3 libdap11
  libdapclient3 libdapserver7 libepsilon1 libfreexl1 libgdal1h libgeos-3.4.2
  libgeos-c1 libgfortran3 libhdf4-0-alt libhdf5-8 libkml0 liblapack3
  libmysqlclient18 libnetcdfc7 libodbc1 libogdi3.2 libpopt0 libpq5 libproj0
  libspatialite5 liburiparser1 libwebp5 libxerces-c3.1 mysql-common odbcinst
  odbcinst1debian2 proj-data
0 upgraded, 33 newly installed, 0 to remove and 124 not upgraded.
Need to get 15.7 MB of archives.
After this operation, 55.3 MB of additional disk space will be used.
Get:1 http://security.debian.org/ jessie/updates/main mysql-common all 5.5.57-0+deb8u1 [84.2 kB]
Get:2 http://security.debian.org/ jessie/updates/main libmysqlclient18 amd64 5.5.57-0+deb8u1 [680 kB]
Get:3 http://security.debian.org/ jessie/updates/main libpq5 amd64 9.4.13-0+deb8u1 [126 kB]
Get:4 http://httpredir.debian.org/debian/ jessie/main libpopt0 amd64 1.16-10 [49.2 kB]
Get:5 http://httpredir.debian.org/debian/ jessie/main libdap11 amd64 3.12.0-1 [344 kB]
Get:6 http://httpredir.debian.org/debian/ jessie/main libdapclient3 amd64 3.12.0-1 [157 kB]
Get:7 http://httpredir.debian.org/debian/ jessie/main libdapserver7 amd64 3.12.0-1 [98.9 kB]
Get:8 http://httpredir.debian.org/debian/ jessie/main libepsilon1 amd64 0.9.2-2 [41.2 kB]
Get:9 http://httpredir.debian.org/debian/ jessie/main libgfortran3 amd64 4.9.2-10 [255 kB]
Get:10 http://httpredir.debian.org/debian/ jessie/main libhdf5-8 amd64 1.8.13+docs-15+deb8u1 [1,061 kB]
Get:11 http://httpredir.debian.org/debian/ jessie/main libodbc1 amd64 2.3.1-3 [206 kB]
Get:12 http://httpredir.debian.org/debian/ jessie/main libxerces-c3.1 amd64 3.1.1-5.1+deb8u3 [865 kB]
Get:13 http://httpredir.debian.org/debian/ jessie/main odbcinst amd64 2.3.1-3 [41.9 kB]
Get:14 http://httpredir.debian.org/debian/ jessie/main odbcinst1debian2 amd64 2.3.1-3 [72.6 kB]
Get:15 http://httpredir.debian.org/debian/ jessie/main libfreexl1 amd64 1.0.0g-1+deb8u3 [26.5 kB]
Get:16 http://httpredir.debian.org/debian/ jessie/main libgeos-3.4.2 amd64 3.4.2-6 [564 kB]
Get:17 http://httpredir.debian.org/debian/ jessie/main libgeos-c1 amd64 3.4.2-6 [172 kB]
Get:18 http://httpredir.debian.org/debian/ jessie/main proj-data amd64 4.8.0-5 [2,085 kB]
Get:19 http://httpredir.debian.org/debian/ jessie/main libproj0 amd64 4.8.0-5 [144 kB]
Get:20 http://httpredir.debian.org/debian/ jessie/main libspatialite5 amd64 4.1.1-10 [871 kB]
Get:21 http://httpredir.debian.org/debian/ jessie/main libwebp5 amd64 0.4.1-1.2+b2 [201 kB]
Get:22 http://httpredir.debian.org/debian/ jessie/main libblas-common amd64 1.2.20110419-10 [8,496 B]
Get:23 http://httpredir.debian.org/debian/ jessie/main libblas3 amd64 1.2.20110419-10 [167 kB]
Get:24 http://httpredir.debian.org/debian/ jessie/main liblapack3 amd64 3.5.0-4 [1,852 kB]
Get:25 http://httpredir.debian.org/debian/ jessie/main libarpack2 amd64 3.1.5-3 [97.8 kB]
Get:26 http://httpredir.debian.org/debian/ jessie/main libarmadillo4 amd64 1:4.450.2+dfsg-1 [72.2 kB]
Get:27 http://httpredir.debian.org/debian/ jessie/main libnetcdfc7 amd64 1:4.1.3-7.2 [276 kB]
Get:28 http://httpredir.debian.org/debian/ jessie/main liburiparser1 amd64 0.8.0.1-2 [41.0 kB]
Get:29 http://httpredir.debian.org/debian/ jessie/main libhdf4-0-alt amd64 4.2.10-3 [271 kB]
Get:30 http://httpredir.debian.org/debian/ jessie/main libkml0 amd64 1.3.0~r864+dfsg-1 [313 kB]
Get:31 http://httpredir.debian.org/debian/ jessie/main libogdi3.2 amd64 3.2.0~beta2-7.1 [212 kB]
Get:32 http://httpredir.debian.org/debian/ jessie/main libgdal1h amd64 1.10.1+dfsg-8+b3 [3,921 kB]
Get:33 http://httpredir.debian.org/debian/ jessie/main gdal-bin amd64 1.10.1+dfsg-8+b3 [330 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 15.7 MB in 3s (4,092 kB/s)
Selecting previously unselected package libpopt0:amd64.
(Reading database ... 78974 files and directories currently installed.)
Preparing to unpack .../libpopt0_1.16-10_amd64.deb ...
Unpacking libpopt0:amd64 (1.16-10) ...
Selecting previously unselected package libdap11:amd64.
Preparing to unpack .../libdap11_3.12.0-1_amd64.deb ...
Unpacking libdap11:amd64 (3.12.0-1) ...
Selecting previously unselected package libdapclient3:amd64.
Preparing to unpack .../libdapclient3_3.12.0-1_amd64.deb ...
Unpacking libdapclient3:amd64 (3.12.0-1) ...
Selecting previously unselected package libdapserver7:amd64.
Preparing to unpack .../libdapserver7_3.12.0-1_amd64.deb ...
Unpacking libdapserver7:amd64 (3.12.0-1) ...
Selecting previously unselected package libepsilon1:amd64.
Preparing to unpack .../libepsilon1_0.9.2-2_amd64.deb ...
Unpacking libepsilon1:amd64 (0.9.2-2) ...
Selecting previously unselected package libgfortran3:amd64.
Preparing to unpack .../libgfortran3_4.9.2-10_amd64.deb ...
Unpacking libgfortran3:amd64 (4.9.2-10) ...
Selecting previously unselected package libhdf5-8:amd64.
Preparing to unpack .../libhdf5-8_1.8.13+docs-15+deb8u1_amd64.deb ...
Unpacking libhdf5-8:amd64 (1.8.13+docs-15+deb8u1) ...
Selecting previously unselected package mysql-common.
Preparing to unpack .../mysql-common_5.5.57-0+deb8u1_all.deb ...
Unpacking mysql-common (5.5.57-0+deb8u1) ...
Selecting previously unselected package libmysqlclient18:amd64.
Preparing to unpack .../libmysqlclient18_5.5.57-0+deb8u1_amd64.deb ...
Unpacking libmysqlclient18:amd64 (5.5.57-0+deb8u1) ...
Selecting previously unselected package libodbc1:amd64.
Preparing to unpack .../libodbc1_2.3.1-3_amd64.deb ...
Unpacking libodbc1:amd64 (2.3.1-3) ...
Selecting previously unselected package libpq5:amd64.
Preparing to unpack .../libpq5_9.4.13-0+deb8u1_amd64.deb ...
Unpacking libpq5:amd64 (9.4.13-0+deb8u1) ...
Selecting previously unselected package libxerces-c3.1:amd64.
Preparing to unpack .../libxerces-c3.1_3.1.1-5.1+deb8u3_amd64.deb ...
Unpacking libxerces-c3.1:amd64 (3.1.1-5.1+deb8u3) ...
Selecting previously unselected package odbcinst.
Preparing to unpack .../odbcinst_2.3.1-3_amd64.deb ...
Unpacking odbcinst (2.3.1-3) ...
Selecting previously unselected package odbcinst1debian2:amd64.
Preparing to unpack .../odbcinst1debian2_2.3.1-3_amd64.deb ...
Unpacking odbcinst1debian2:amd64 (2.3.1-3) ...
Selecting previously unselected package libfreexl1:amd64.
Preparing to unpack .../libfreexl1_1.0.0g-1+deb8u3_amd64.deb ...
Unpacking libfreexl1:amd64 (1.0.0g-1+deb8u3) ...
Selecting previously unselected package libgeos-3.4.2.
Preparing to unpack .../libgeos-3.4.2_3.4.2-6_amd64.deb ...
Unpacking libgeos-3.4.2 (3.4.2-6) ...
Selecting previously unselected package libgeos-c1.
Preparing to unpack .../libgeos-c1_3.4.2-6_amd64.deb ...
Unpacking libgeos-c1 (3.4.2-6) ...
Selecting previously unselected package proj-data.
Preparing to unpack .../proj-data_4.8.0-5_amd64.deb ...
Unpacking proj-data (4.8.0-5) ...
Selecting previously unselected package libproj0.
Preparing to unpack .../libproj0_4.8.0-5_amd64.deb ...
Unpacking libproj0 (4.8.0-5) ...
Selecting previously unselected package libspatialite5:amd64.
Preparing to unpack .../libspatialite5_4.1.1-10_amd64.deb ...
Unpacking libspatialite5:amd64 (4.1.1-10) ...
Selecting previously unselected package libwebp5:amd64.
Preparing to unpack .../libwebp5_0.4.1-1.2+b2_amd64.deb ...
Unpacking libwebp5:amd64 (0.4.1-1.2+b2) ...
Selecting previously unselected package libblas-common.
Preparing to unpack .../libblas-common_1.2.20110419-10_amd64.deb ...
Unpacking libblas-common (1.2.20110419-10) ...
Selecting previously unselected package libblas3.
Preparing to unpack .../libblas3_1.2.20110419-10_amd64.deb ...
Unpacking libblas3 (1.2.20110419-10) ...
Selecting previously unselected package liblapack3.
Preparing to unpack .../liblapack3_3.5.0-4_amd64.deb ...
Unpacking liblapack3 (3.5.0-4) ...
Selecting previously unselected package libarpack2.
Preparing to unpack .../libarpack2_3.1.5-3_amd64.deb ...
Unpacking libarpack2 (3.1.5-3) ...
Selecting previously unselected package libarmadillo4.
Preparing to unpack .../libarmadillo4_1%3a4.450.2+dfsg-1_amd64.deb ...
Unpacking libarmadillo4 (1:4.450.2+dfsg-1) ...
Selecting previously unselected package libnetcdfc7.
Preparing to unpack .../libnetcdfc7_1%3a4.1.3-7.2_amd64.deb ...
Unpacking libnetcdfc7 (1:4.1.3-7.2) ...
Selecting previously unselected package liburiparser1.
Preparing to unpack .../liburiparser1_0.8.0.1-2_amd64.deb ...
Unpacking liburiparser1 (0.8.0.1-2) ...
Selecting previously unselected package libhdf4-0-alt.
Preparing to unpack .../libhdf4-0-alt_4.2.10-3_amd64.deb ...
Unpacking libhdf4-0-alt (4.2.10-3) ...
Selecting previously unselected package libkml0:amd64.
Preparing to unpack .../libkml0_1.3.0~r864+dfsg-1_amd64.deb ...
Unpacking libkml0:amd64 (1.3.0~r864+dfsg-1) ...
Selecting previously unselected package libogdi3.2.
Preparing to unpack .../libogdi3.2_3.2.0~beta2-7.1_amd64.deb ...
Unpacking libogdi3.2 (3.2.0~beta2-7.1) ...
Selecting previously unselected package libgdal1h.
Preparing to unpack .../libgdal1h_1.10.1+dfsg-8+b3_amd64.deb ...
Unpacking libgdal1h (1.10.1+dfsg-8+b3) ...
Selecting previously unselected package gdal-bin.
Preparing to unpack .../gdal-bin_1.10.1+dfsg-8+b3_amd64.deb ...
Unpacking gdal-bin (1.10.1+dfsg-8+b3) ...
Setting up libpopt0:amd64 (1.16-10) ...
Setting up libdap11:amd64 (3.12.0-1) ...
Setting up libdapclient3:amd64 (3.12.0-1) ...
Setting up libdapserver7:amd64 (3.12.0-1) ...
Setting up libepsilon1:amd64 (0.9.2-2) ...
Setting up libgfortran3:amd64 (4.9.2-10) ...
Setting up libhdf5-8:amd64 (1.8.13+docs-15+deb8u1) ...
Setting up mysql-common (5.5.57-0+deb8u1) ...
Setting up libmysqlclient18:amd64 (5.5.57-0+deb8u1) ...
Setting up libodbc1:amd64 (2.3.1-3) ...
Setting up libpq5:amd64 (9.4.13-0+deb8u1) ...
Setting up libxerces-c3.1:amd64 (3.1.1-5.1+deb8u3) ...
Setting up libfreexl1:amd64 (1.0.0g-1+deb8u3) ...
Setting up libgeos-3.4.2 (3.4.2-6) ...
Setting up libgeos-c1 (3.4.2-6) ...
Setting up proj-data (4.8.0-5) ...
Setting up libproj0 (4.8.0-5) ...
Setting up libspatialite5:amd64 (4.1.1-10) ...
Setting up libwebp5:amd64 (0.4.1-1.2+b2) ...
Setting up libblas-common (1.2.20110419-10) ...
Setting up libblas3 (1.2.20110419-10) ...
update-alternatives: using /usr/lib/libblas/libblas.so.3 to provide /usr/lib/libblas.so.3 (libblas.so.3) in auto mode
Setting up liblapack3 (3.5.0-4) ...
update-alternatives: using /usr/lib/lapack/liblapack.so.3 to provide /usr/lib/liblapack.so.3 (liblapack.so.3) in auto mo
de
Setting up libarpack2 (3.1.5-3) ...
Setting up libarmadillo4 (1:4.450.2+dfsg-1) ...
Setting up libnetcdfc7 (1:4.1.3-7.2) ...
Setting up liburiparser1 (0.8.0.1-2) ...
Setting up libhdf4-0-alt (4.2.10-3) ...
Setting up libkml0:amd64 (1.3.0~r864+dfsg-1) ...
Setting up libogdi3.2 (3.2.0~beta2-7.1) ...
Setting up odbcinst1debian2:amd64 (2.3.1-3) ...
Setting up libgdal1h (1.10.1+dfsg-8+b3) ...
Setting up gdal-bin (1.10.1+dfsg-8+b3) ...
Setting up odbcinst (2.3.1-3) ...
Processing triggers for libc-bin (2.19-18+deb8u3) ...
 ---> 84367be80fec
Removing intermediate container bdb6b3f46fad
Step 5/9 : USER $NB_USER
 ---> Running in 253b6b8cc324
 ---> 95286b1ddf2a
Removing intermediate container 253b6b8cc324
Step 6/9 : RUN conda install --quiet --yes -c conda-forge ipyleaflet &&     conda clean -tipsy
 ---> Running in 9ea448b6aeab
Fetching package metadata: ......
Solving package specifications: .........
Enabling notebook extension jupyter-leaflet/extension...
      - Validating: OK

Package plan for installation in environment /opt/conda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0         1017 B
    libffi-3.2.1               |                3          47 KB
    ncurses-5.9                |               10         1.1 MB
    sqlite-3.13.0              |                0         4.9 MB
    xz-5.2.2                   |                0         853 KB
    python-3.5.4               |                0        18.5 MB
    asn1crypto-0.22.0          |           py35_0         149 KB
    certifi-2017.7.27.1        |           py35_0         204 KB
    idna-2.6                   |           py35_0         123 KB
    pycparser-2.18             |           py35_0         169 KB
    requests-2.12.4            |           py35_0         989 KB
    ruamel_yaml-0.11.14        |           py35_1         395 KB
    cffi-1.10.0                |           py35_0         388 KB
    traitlets-4.3.1            |           py35_0         597 KB
    cryptography-1.9           |           py35_0         937 KB
    nbformat-4.2.0             |           py35_0         587 KB
    pyopenssl-17.0.0           |           py35_0          76 KB
    conda-4.3.24               |           py35_0         516 KB
    ipykernel-4.5.1            |           py35_0         1.3 MB
    notebook-4.4.1             |           py35_0         6.2 MB
    widgetsnbextension-2.0.0   |           py35_0         875 KB
    ipywidgets-6.0.0           |           py35_0         527 KB
    ipyleaflet-0.3.0           |           py35_0         776 KB
    ------------------------------------------------------------
                                           Total:        39.9 MB

The following NEW packages will be INSTALLED:

    asn1crypto:         0.22.0-py35_0
    certifi:            2017.7.27.1-py35_0
    cffi:               1.10.0-py35_0
    cryptography:       1.9-py35_0
    idna:               2.6-py35_0
    ipyleaflet:         0.3.0-py35_0
    libffi:             3.2.1-3
    ncurses:            5.9-10
    pycparser:          2.18-py35_0
    pyopenssl:          17.0.0-py35_0
    ruamel_yaml:        0.11.14-py35_1
    widgetsnbextension: 2.0.0-py35_0

The following packages will be UPDATED:

    conda:              4.0.5-py35_0 --> 4.3.24-py35_0
    conda-env:          2.4.5-py35_0 --> 2.6.0-0
    ipykernel:          4.3.1-py35_0 --> 4.5.1-py35_0
    ipywidgets:         4.1.1-py35_0 --> 6.0.0-py35_0
    nbformat:           4.0.1-py35_0 --> 4.2.0-py35_0
    notebook:           4.1.0-py35_1 --> 4.4.1-py35_0
    python:             3.5.1-0      --> 3.5.4-0
    requests:           2.9.1-py35_0 --> 2.12.4-py35_0
    sqlite:             3.9.2-0      --> 3.13.0-0
    traitlets:          4.1.0-py35_0 --> 4.3.1-py35_0
    xz:                 5.0.5-1      --> 5.2.2-0

Cache location: /opt/conda/pkgs
Will remove the following tarballs:

/opt/conda/pkgs
---------------
python-3.5.4-0.tar.bz2                      18.5 MB
cffi-1.10.0-py35_0.tar.bz2                   388 KB
ipywidgets-6.0.0-py35_0.tar.bz2              527 KB
asn1crypto-0.22.0-py35_0.tar.bz2             149 KB
requests-2.12.4-py35_0.tar.bz2               989 KB
conda-4.3.24-py35_0.tar.bz2                  516 KB
nbformat-4.2.0-py35_0.tar.bz2                587 KB
sqlite-3.13.0-0.tar.bz2                      4.9 MB
ruamel_yaml-0.11.14-py35_1.tar.bz2           395 KB
ncurses-5.9-10.tar.bz2                       1.1 MB
xz-5.2.2-0.tar.bz2                           853 KB
traitlets-4.3.1-py35_0.tar.bz2               597 KB
pyopenssl-17.0.0-py35_0.tar.bz2               76 KB
conda-env-2.6.0-0.tar.bz2                    1017 B
cryptography-1.9-py35_0.tar.bz2              937 KB
notebook-4.4.1-py35_0.tar.bz2                6.2 MB
certifi-2017.7.27.1-py35_0.tar.bz2           204 KB
idna-2.6-py35_0.tar.bz2                      123 KB
libffi-3.2.1-3.tar.bz2                        47 KB
widgetsnbextension-2.0.0-py35_0.tar.bz2      875 KB
ipykernel-4.5.1-py35_0.tar.bz2               1.3 MB
ipyleaflet-0.3.0-py35_0.tar.bz2              776 KB
pycparser-2.18-py35_0.tar.bz2                169 KB

---------------------------------------------------
Total:                                      39.9 MB

Removed python-3.5.4-0.tar.bz2
Removed cffi-1.10.0-py35_0.tar.bz2
Removed ipywidgets-6.0.0-py35_0.tar.bz2
Removed asn1crypto-0.22.0-py35_0.tar.bz2
Removed requests-2.12.4-py35_0.tar.bz2
Removed conda-4.3.24-py35_0.tar.bz2
Removed nbformat-4.2.0-py35_0.tar.bz2
Removed sqlite-3.13.0-0.tar.bz2
Removed ruamel_yaml-0.11.14-py35_1.tar.bz2
Removed ncurses-5.9-10.tar.bz2
Removed xz-5.2.2-0.tar.bz2
Removed traitlets-4.3.1-py35_0.tar.bz2
Removed pyopenssl-17.0.0-py35_0.tar.bz2
Removed conda-env-2.6.0-0.tar.bz2
Removed cryptography-1.9-py35_0.tar.bz2
Removed notebook-4.4.1-py35_0.tar.bz2
Removed certifi-2017.7.27.1-py35_0.tar.bz2
Removed idna-2.6-py35_0.tar.bz2
Removed libffi-3.2.1-3.tar.bz2
Removed widgetsnbextension-2.0.0-py35_0.tar.bz2
Removed ipykernel-4.5.1-py35_0.tar.bz2
Removed ipyleaflet-0.3.0-py35_0.tar.bz2
Removed pycparser-2.18-py35_0.tar.bz2
Cache location: /opt/conda/pkgs
Will remove the following packages:
/opt/conda/pkgs
---------------

conda-env-2.6.0-0                              1 KB

---------------------------------------------------
Total:                                         1 KB

removing conda-env-2.6.0-0
source cache (/opt/conda/conda-bld/src_cache)
Size:                                           0 B

svn cache (/opt/conda/conda-bld/svn_cache)
Size:                                           0 B

hg cache (/opt/conda/conda-bld/hg_cache)
Size:                                           0 B

git cache (/opt/conda/conda-bld/git_cache)
Size:                                           0 B

Total:                                          0 B
Removing /opt/conda/conda-bld/src_cache
Removing /opt/conda/conda-bld/svn_cache
Removing /opt/conda/conda-bld/hg_cache
Removing /opt/conda/conda-bld/git_cache
 ---> dda2870f4faf
Removing intermediate container 9ea448b6aeab
Step 7/9 : RUN source $CONDA_DIR/bin/activate python2 &&     conda install --quiet --yes -c conda-forge gdal=2.1.3 crypt
ography ipyleaflet rasterio=1.0a5 &&     conda clean -tipsy &&     pip install --upgrade pip &&     pip install gbdxtool
s                 shapely
 ---> Running in 2f144b8b7c55

PackageNotFoundError: Packages missing in current channels:

  - rasterio 1.0a5*

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch

The command '/bin/sh -c source $CONDA_DIR/bin/activate python2 &&     conda install --quiet --yes -c conda-forge gdal=2.
1.3 cryptography ipyleaflet rasterio=1.0a5 &&     conda clean -tipsy &&     pip install --upgrade pip &&     pip install
 gbdxtools                 shapely' returned a non-zero code: 1

**Comment by kstamatiou** [comment]
@joemcglinchy: Can't help you with Windows issues. All our development is done on Linux/OSX.
